export const ORDER_STATUS = {
  INIT: 'INIT',
  PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
  FULFILLED: 'FULFILLED',
  PAID: 'PAID',
};

export const ORDER_TYPES = {
  RESTURANT: 'RESTURANT',
  TAKE_AWAY: 'TAKE_AWAY',
  DELIVERY: 'DELIVERY',
};
