/* eslint-disable */
require('./credit-card')
require('./dinner')
require('./edit')
require('./food-stall')
require('./groceries')
require('./restaurant')
require('./salad')
require('./stew')
require('./store')
require('./user')
require('./vegetables')
